### ISSUE TITLE
Save Activity details for bids

### ISSUE THREAD

**Issue by AshenI99** [curaOS/subgraph#9]
## Changes

- Activities are not saving in the subgraph for bid related things.

**Comment by TheLubab** [comment]
For this, I think we need to leave `Activity` entity only for the events that directly affects the NFT like (transfer, burn, mint)

The bidding history doesn't matter that much and it doesn't have to be permanent. But the `Bid` entity can be used with history if needed.
![image](https://user-images.githubusercontent.com/54310457/156553699-cc67ef06-f04a-4b89-a2c3-112f057a33ec.png)

**Comment by AshenI99** [comment]
Hi @achrafismyname,
I updated the Activity entity for a better structure here.  #10 
With that, we can efficiently use `set_bid` and `accept_bid` activities without much work.

And also if you look at this example graph, they are storing bid events. And I think with the new structure, we can use store those events easily without taking lot of storage.
https://thegraph.com/hosted-service/subgraph/f8n/fnd
